version: "3.8"

services:
  # mysql database
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  # spring boot app
  spring_app:
    build: ./
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/test_db?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "123456",
        "spring.datasource.driver-class-name" : "com.mysql.cj.jdbc.Driver"}'
    volumes:
      - .m2:/root/.m2

volumes:
  db: